### ISSUE TITLE
Кэширование

### ISSUE THREAD

**Issue by LinkSayrus** [vmasalov/seasonvar.bundle#10]
Подскажите пожалуйста такой момент.
У нас интернет не очень хороший и я заметил что кэширование сериала происходит частями. 
Т.е. серию включил, нажал на паузу, начинается загрузка,  когда загрузка доходит до конца части кэширование останавливается. Включаешь просмотр и когда просмотр доходит до конца текущей части, которая загрузилась, начинается загрузка следующей части при этом соответственно серия начинает тормозить и далее т.д.

Есть ли возможность выставить чтобы после окончания загрузки первой части сразу же начиналась загружаться следующая часть?
Или это зависит от самого телевизора?

А то просмотр одной серии занимает целую вечность с этими паузами.

Или может как-то поменять настройки и выбрать качество в ручную? а то как я понимаю HD для моего инета это слишком.

**Comment by vmasalov** [comment]
Насколько я понимаю, это завистит даже не от телевизора, а от Plex Media Server и как он работает с загрузкой видео. По сути, плагин только находит нужный файл для проигрывания, а дальше он отдает его на "обработку". 

Так же, seasonvar отдает ссылку на где не указано качество и размер. Поэтому я не могу оптимально создавать видео контейнер для HD файлов. ( было так раньше 100%, сейчас не могу проверить, но раз плагин работает - то скорее всего они ничего не меняли )

Попробуй настроить сервер через настройки ( Settings -> Server -> Show Advanced -> Transcoder ) там можешь указать качество видео. Это секция влияет на скорость с которой происходит раскодирование видео.

Так же, настрой качество плеера. Settings -> Web -> Quality и уменьши качество видео.

**Comment by LinkSayrus** [comment]
У меня само приложение Plex стоит на старом самсунговском bd плеере и когда я отслеживал нагрузку по сети, то четко было видно что загрузка идет именно с ip этого плеера а не Plex Servera. 

Я в принципе в плагине поменял параметр video_resolution на 720 и стало получше работать. 

Просто на сколько я понимаю если я поменяю на сервере настройки качества тогда у меня даже локальное видео будет в хреновом качестве показываться. а мне этого не надо.

**Comment by vmasalov** [comment]
Хм, интересно... Наверное лучшее что можно сделать - это добавить опцию выбора качества в настройках. И таким образом можно указать будет video_resolution без необходимости изменения кода.

По поводу изменения качества на самом сервере, то локальное видео будет плохого качества тоже... увы.

**Comment by vmasalov** [comment]
Я создал новую ветку `feature/implement-video-resolution` которая содержит код для установки `video_resolution` через настройки. Вроде как работает, если не сложно - можете протестировать?

**Comment by LinkSayrus** [comment]
Да работает!!!

Есть еще один момент. Плагин работает только на английском языке. Причем весь Plex настроен везде на русский. 
Помогает только замена ru.json на en.json

**Comment by vmasalov** [comment]
Поправил локализацию. Теперь должно работать корректно. Если не сложно, проверь и если работает - я закомичу

**Comment by LinkSayrus** [comment]
Локализация работает. Стало по русски. Спасибо. 

Раз такая пьянка еще один вопрос :))) 
Т.к. seasonvar блокирует сериалы по запросу от обладателей для пользователей с России и из-за этого некоторые сериалы работают только через прокси других стран, реально ли в конфиге реализовать настройки прокси? или не получится т.к. загрузка зависит полностью от плеера с которого просмотр идет?

**Comment by vmasalov** [comment]
Да я замечал такую фишку c блокировкой и самое простое - это настроить VPN (openvpn) соединение на сервере где работает Plex Media Server. Может быть еще прописать пару правил на firewall что-бы порты нужные были.

Просто на уровне плагина - это довольно сложно реализовать, есть пара модулей на python которые позволяют реализовать VPN соединение, но это уже не тривиальное изменение, которое требует изменения Plex Framework и нет ни какой гарантии, что не отвалиться при следующем обнавлении сервера

Поэтому, мое мнение - проще на серваке включать VPN и не париться. Вот [ветка на форуме](https://forums.plex.tv/discussion/64600/using-plex-server-with-a-vpn) где обсуждается как это все настроить.
