### ISSUE TITLE
Работа плагина

### ISSUE THREAD

**Issue by LinkSayrus** [vmasalov/seasonvar.bundle#12]
Добрый день. Я видимо поторопился подтвердив что плагин работает после внесения изменений. 

В общем после изменения с локализацией русского языка плагин на каналах которые, не добавлены в избранное, выдает везде "Канал не отвечает" 
А те которые добавлены в избранное работают через раз. 

Если ставить версию предыдущую где добавлено только изменения качества в настройки, тогда все работает.

**Comment by ArStudio** [comment]
@LinkSayrus поделитесь, пожалуйста, рабочей версией. Потому что на 1.8 при попытке открыть любой сериал - "Этот канал не отвечает." :(

**Comment by vmasalov** [comment]
Откатил версию без локализации на master branch.
Должно работать

**Comment by ArStudio** [comment]
@vmasalov спасибо! заработало
