### ISSUE TITLE
Subs are not working

### ISSUE THREAD

**Issue by hapkom2k** [vmasalov/seasonvar.bundle#13]
Привет, спасибо огромное за плагин! Все работает, за исключением субтитров. Plex их не видит. Я думал, что они встроены в видео, но нет. Есть способ их включить?

--------------------------------------
Hello, thank you very much for the plugin! Everything works, except for the subtitles. Plex can't see them. I thought they were embedded in the video, but no. Is there a way to turn them on?

**Comment by hapkom2k** [comment]
Посмотрел код, субтитры в Todo =)) 
Когда ждать добавления?

**Comment by vmasalov** [comment]
На данный момент я не планировал добавлять субтитры так как нужно дебажить, а мой премиум аккаунт закончился и доступа к API нету )

**Comment by hapkom2k** [comment]
Могу предоставить премиум или ключ API. Очень не хватает сабов.

**Comment by vmasalov** [comment]
В общем мне нужен твой email, гитхаб убрал приватные сообщения. Я не знаю как тебе написать. Я тебе напишу с этого мыла masalow.subscribe@gmail.com

> Я удалю это сообщение как только пришлешь свое.

**Comment by vmasalov** [comment]
В общем закрываю ветку потому как Plex не поддерживает субтитры в каналах.
Я тут ничего не могу сделать без изменения кода самого Plex Server.

Как обычно, документации мало... пришлось ковырять серверный код и читать форум.
В добавок ко всему - нужно что бы субтитры имели такое же имя как и файл сериала. А в случае seasonvar они видео тянут с одного CDN, а субтитры с другого + имена файлов разные... В общем полная анархия, увы - ничего не поделать на данный момент не могу.
