### ISSUE TITLE
Разные сезоны одного сериала в Закладках

### ISSUE THREAD

**Issue by ArStudio** [vmasalov/seasonvar.bundle#14]
Спасибо за плагин! Все работает, но заметил такую особенность. Если в Закладках уже есть один сезон сериала, то другой сезон этого сериала не получается добавить. Вместо кнопки "Добавить в закладки" отображается только "Удалить из закладок". Но такая ситуация не всегда. Часто кнопка "Добавить в закладки" есть, но после ее нажатия, этот сезон в Закладках появляется только после того, как удалишь тот сезон, который там уже был. Получается, несколько сезонов одного сериала не получается добавить в Закладки.

**Comment by vmasalov** [comment]
Исправлено в 1.9
