### ISSUE TITLE
Отключаемые кнопки

### ISSUE THREAD

**Issue by ArStudio** [vmasalov/seasonvar.bundle#17]
Большая просьба добавить в настройки плагина возможность отключать кнопки редактирования закладок.

Дело в том, что когда добавляешь, например, в библиотеку Infuse (через UPnP/DLNA) папку с сериалом, то при сканировании кнопка _Удалить из закладок_ срабатывает и сериал соответственно удаляется из Закладок.

Такой чекбокс решил бы эту проблему...
![image](https://user-images.githubusercontent.com/13891712/45800966-29bda200-bcbb-11e8-965f-acfae37d0e8a.png)

PS Еще раз спасибо за плагин! Не знаю сколько людей пользуется им, но я использую его в связке с Apple TV и Infuse и очень доволен. )

**Comment by vmasalov** [comment]
О прикольная фишка... Сейчас добавим, должно быть просто

**Comment by vmasalov** [comment]
В общем, сделал отдельную ветку feature/configure-clear-bookmarks-button
Протестируй и дай знать работает или нет

**Comment by ArStudio** [comment]
Не вижу ветку. Где искать?

**Comment by vmasalov** [comment]
https://github.com/vmasalov/seasonvar.bundle/tree/feature/configure-clear-bookmarks-button

**Comment by ArStudio** [comment]
Чекбокс появился, но включен он или нет - ничего не меняется. Кнопки на месте и работают.

**Comment by ArStudio** [comment]
Так что, не получится это реализовать?

**Comment by vmasalov** [comment]
Исправил - проверь, должно работать вроде как

**Comment by ArStudio** [comment]
Да, теперь работает. Спасибо!
