### ISSUE TITLE
Будет ли работать плагин после окончания подписки?

### ISSUE THREAD

**Issue by chasylexus** [vmasalov/seasonvar.bundle#2]
Добрый день.
Если купить подписку на месяц, плагин будет работать только месяц?
Вот здесь: https://github.com/burgua/kodi-seasonvar-plugin насколько я понимаю, плагин для Kodi, который работает без подписки.

**Comment by vmasalov** [comment]
День добрый,
На данный момент плагин работает только с премиум аккаунтами, так как использует Seasonvar 
API для получения данных. Cпасибо за ссылку, я гляну как они парсят список который приходит с сервера и внесу изменения.

**Comment by chasylexus** [comment]
Если получится, будет здорово :)

**Comment by chasylexus** [comment]
Ещё есть вот что:
https://github.com/nikoncode/node-seasonvar
https://github.com/crossdot/seasonvar-api

**Comment by vmasalov** [comment]
Ок гляну, я как раз этим и занимаюсь, так как у меня самого закончилась  подписка... )

**Comment by chasylexus** [comment]
Пока новостей нет? :)

**Comment by vmasalov** [comment]
Не, пока что не было времени.
Улучшил пока что premium версию

**Comment by vmasalov** [comment]
В общем у меня нет сейчас времени писать парсер для не Premium. Рекомендую следующий подход (если влом покупать) http://seasonvar.ru/premDar.php и чудесный сервис mailinator.com вместе работает замечательно )
