### ISSUE TITLE
Как смотреть в HD качестве?

### ISSUE THREAD

**Issue by Moncrieff** [vmasalov/seasonvar.bundle#3]
Спасибо за плагин. 
Всё работает, но есть одна проблема - все сериалы транслируются в SD качестве. Как можно это исправить? С сайта смотреть в HD можно.

Заранее спасибо.

**Comment by vmasalov** [comment]
Я увеличил video_resolution для контейнера на 1080. Должно улучшить качество... но это макс. что я могу сделать, так как seasonvar выдает только одну ссылку для проигрывания (((

**Comment by vmasalov** [comment]
Дай знать если нет разницы, я может еще покавыряю чего
