### ISSUE TITLE
Перестал работать плагин 

### ISSUE THREAD

**Issue by shoguevara** [vmasalov/seasonvar.bundle#8]
При попытке воспроизведения потока пишет 
An error occurred trying to play "1 серия".
shaka1001 (Network)

Премиум активен, эпизоды браузятся нормально. В остальных клиентах (plex-connect, samsungTV app, Bravia app) в лучшем случае жалуется на таймаут.

https://pastebin.com/kFCkhmPC

**Comment by vmasalov** [comment]
Гляну, наверное что-то опять изменили

**Comment by vmasalov** [comment]
А ты можешь проверить эту ветку?
https://github.com/vmasalov/seasonvar.bundle/tree/bugfix/extra_args

Я вроде починил, но не могу проверить ))) у меня нету премиум аккаунта (закончился)

**Comment by shoguevara** [comment]
Чего-то вообще плагин не подгружается.
Кинь в личку код - посмотрим что можно сделать с твоим премиумом =)
Сам тоже им только для гостей пользуюсь - сам смотрю на инглише через torrrenttv
https://pastebin.com/BPtLNRy6
и https://pastebin.com/ZeGLPdQK

**Comment by vmasalov** [comment]
Поправил - у меня по крайней мере появился в меню и грузится
Но проверить не могу, так как нету кода у самого

**Comment by shoguevara** [comment]
Увы и ах... А про код я говорил, который в смс надо им отправить
https://pastebin.com/xp3n3QTh
Все еще не отображается в списке
Кэши и настройки чистил

**Comment by vmasalov** [comment]
погоди, там ошибка в отступе - сейчас поправлю. Поэтому не грузится плагин

**Comment by vmasalov** [comment]
Поправил, должно теперь работать.

**Comment by shoguevara** [comment]
Все работает! Спасибо!
Как отблагодарить за труд то?

**Comment by vmasalov** [comment]
Поставь лайк проекту )

**Comment by shoguevara** [comment]
Со звездочкой уж больше года точно =)
